### ISSUE TITLE
Allow custom configured Ds3ClientImpl

### ISSUE THREAD

**Issue by dkocher** [SpectraLogic/ds3_java_sdk#173]
Can you apply 0e8b9cdd6d58ba3a29dbb14309693e62f09fea56 to the 3.0 branch.

**Comment by rpmoore** [comment]
This change was ommited from our new autogen project.  I'll make sure it gets updated there and then here.  Thanks for catching this!

**Comment by rpmoore** [comment]
Please use version v3.0.0-RC5 which makes this constructor public in the auto-generated code.
