### ISSUE TITLE
Missing Length and Offset parameters in START_BULK_GET operation

### ISSUE THREAD

**Issue by dkocher** [SpectraLogic/ds3_java_sdk#196]
> 
An XML payload, formatted as follows, must be sent to describe the GET job to create:
```
<Objects 
<Object Name="{string}" Length="{64-bit integer}"  
Offset="{64-bit integer}"/>  ... 
</Objects>
```

When using `Ds3ClientHelpers#startReadJob` it is not possible to pass an offset parameter and the length attribute is not serialized either.

That would be required to support reads with an offset.

**Comment by rpmoore** [comment]
Start bulk get does not support length nor offset in the payload sent to the server.  They are sent in the response body, and are determined by the values stored in black pearl.

**Comment by dkocher** [comment]
That contradicts the documentation.

**Comment by rpmoore** [comment]
Which documentation are you referring to?

**Comment by dkocher** [comment]
BlackPearl S3 Api Reference _Chapter 7 – Job Operations – Create Bulk Get – Request Elements_.

**Comment by dkocher** [comment]
The client may not want to read the full length of an object but request a partial range (regardless of the segmenting returned by the server when objects are split for read).

**Comment by rpmoore** [comment]
This is used for partial gets.  Let me confirm, but support for partial gets should be working. I will verify that our tests are in place and running.  I'll then past a link to an example showing how to do it.

**Comment by rpmoore** [comment]
Here is the link to the example: https://github.com/SpectraLogic/ds3_java_sdk/blob/3_0_autogen/ds3-sdk-samples/src/main/java/com/spectralogic/ds3client/samples/PartialObjectGetExample.java

And the tests are there and working as far as I can tell.  If they are not working as expected I'll reopen after I confirm.

**Comment by dkocher** [comment]
Please check the following usage:
- Start a bulk get for a partial `GET`. I would expect it to send the length and offset to the server.
- Query the job status using `GetAvailableJobChunksRequest`. It will return the wrong offset and length in the returned object list because it is not aware the`GET` should be a partial request.

**Comment by rpmoore** [comment]
This is more or less expected.  Black Pearl still has to fetch the entire blob offset from tape in order to fulfill the request which is why it doesn't look like it's respecting the partial range.  However, when retrieving the file with the Get Object command, it will respect the [Range](https://github.com/SpectraLogic/ds3_java_sdk/blob/3_0_autogen/ds3-sdk/src/main/java/com/spectralogic/ds3client/commands/GetObjectRequest.java#L131) parameter.  If you are using the Helper functions and you pass in PartialObjects, it will perform all the logic required to correctly retrieve the partial ranges.

**Comment by dkocher** [comment]
This is brainfuck and makes the API overly complicated (look at your implementation in `PartialObjectHelpers`). The server should handle the offsets in its replies without the need of the client to merge these client requested ranges and server chunk ranges.

**Comment by dkocher** [comment]
Or I might just not understand the API. Does the gateway expect a offset URI parameter of `0` for requests with a `Range` header?

**Comment by dkocher** [comment]
@rpmoore Sorry to bug you with API related questions here.

**Comment by rpmoore** [comment]
Ranges are fun to deal with... If you have a range that is in a blob with a non-zero offset, you must specify that offset.  Basically the way partial gets work is that you request the ranges that you want to receive in the bulk put.  Then when issuing the Gets, you specify all the Ranges that are in that blob.  Black Pearl will mark the blob as having been received with the first Get to that offset completes.  This is why in the helper functions we merge all the ranges where we can, and will issue a single Get request per-blob.
