### ISSUE TITLE
Misleading status in GetAvailableJobChunksResponse

### ISSUE THREAD

**Issue by dkocher** [SpectraLogic/ds3_java_sdk#246]
When reading a job status with a **non empty** master object list returned but a `Retry-After` header in the response, the status in `GetAvailableJobChunksResponse` will be set to `AVAILABLE` regardless. Not sure if this is a bug, but from my understanding the `Retry-After` header should always be taken into account.

**Comment by dkocher** [comment]
This is possibly more of an API issue, as one would possibly except a `503` reply.

**Comment by rpmoore** [comment]
The Retry-After header is always sent.  Regardless of what the status is.

**Comment by rpmoore** [comment]
It used to be that the `Retry-After` header would only exist when a `503` was returned.  This was changed a while ago in one of the 1.x releases.  So you shouldn't be using the existence of the `Retry-After` header for any branching logic.  Instead use the `status`.

**Comment by dkocher** [comment]
Unfortunately this is counter intuitive as it contracts HTTP.

> The Retry-After response-header field can be used with a 503 (Service Unavailable) response to indicate how long the service is expected to be unavailable to the requesting client. This field MAY also be used with any 3xx (Redirection) response

**Comment by rpmoore** [comment]
I'll pass it a long to the Black Pearl team, but unfortunately this is the current behavior.

**Comment by dkocher** [comment]
@rpmoore Thanks for your clarifications!
