### ISSUE TITLE
ds3-interfaces 4.1.0 missing from bintray repo

### ISSUE THREAD

**Issue by andrewgee** [SpectraLogic/ds3_java_sdk#545]
Hi. We can't seem to find the jar for ds3-interfaces 4.1.0 in bintray:
http://dl.bintray.com/spectralogic/ds3/com/spectralogic/ds3/ds3-interfaces/4.1.0/

**Comment by rpmoore** [comment]
Something must have happened with the upload.  I'll get to this as soon as possible.

**Comment by rpmoore** [comment]
@andrewgee I have uploaded the interface jar file.  Let me know if you continue to run into issues, or experience any other problems.
